### ISSUE TITLE
Add the ability to ignore certain properties - e.g. width

### ISSUE THREAD

**Issue by billyjacoby** [imranbarbhuiya/figma-tailwindcss#2]
### Feature

Would love the ability to not export certain properties - for example the width of the selected component.

### Ideal solution or implementation

Not familiar with developing Figma plugins, but implementing an array of certain properties to ignore when converting to Tailwind is my first thought.

**Comment by imranbarbhuiya** [comment]
I'll try it on my weekend, if it can be done with existing plugin options, I'll add the feature but if it requires creating a plugin UI to add new options then unfortunately I wont be able to implement

**Comment by imranbarbhuiya** [comment]
I know it took some time as I was busy with my projects, but today I added a small UI where you can add a property name or name=value to ignore a property. Check https://github.com/imranbarbhuiya/figma-tailwindcss#features to learn more. The UI is just HTML with no styles. If anyone is interested in styling it, you are more than welcome to do so.

**Comment by billyjacoby** [comment]
Love this addition, thank you! I'm going to look into making it so that I can blanked ignore, for example, every value for the `width` key!

**Comment by billyjacoby** [comment]
https://github.com/imranbarbhuiya/figma-tailwindcss/pull/3
